#!/usr/bin/env python3
"""Remove a generated HUD sheet's magenta matte and package registered OZT sprites.

Usage: python3 tools/pack_hud_atlas.py SOURCE.png THEME_DIRECTORY
The input is the documented four-column, three-row Black Glass source sheet.
"""

import argparse
from pathlib import Path

from PIL import Image, ImageFilter, ImageOps

from png_to_ozt import encode

CELL_SIZE = 256
SPRITE_SIZE = 224
GUTTER = 16
KEY_TOLERANCE = 20
MIN_ALPHA = 16
SPRITES = (
    "glass-crystal", "glass-rim", "glass-slot", "glass-selected",
    "glass-shop", "glass-character", "glass-inventory", "glass-friends",
    "glass-menu", "glass-tube", "glass-rail", "glass-panel",
)


def unmatte(image):
    """Recover straight alpha from a magenta matte, including antialiased edges.

    These neutral metal/stone assets have no intrinsic magenta. The green
    channel estimates foreground coverage; subtract the magenta contribution
    before storing RGB, preventing pink fringes after texture filtering.
    """
    pixels = []
    for red, green, blue in image.convert("RGB").getdata():
        matte = min(red, blue) - green
        if matte < KEY_TOLERANCE:
            pixels.append((red, green, blue, 255))
            continue
        alpha = 255 - matte
        if alpha < MIN_ALPHA:
            pixels.append((0, 0, 0, 0))
            continue
        recover = lambda value: max(0, min(255, round(value * 255 / alpha)))
        pixels.append((recover(red - matte), recover(green), recover(blue - matte), alpha))
    result = Image.new("RGBA", image.size)
    result.putdata(pixels)
    return result


def extract_cells(source):
    if source.width * 3 != source.height * 4:
        raise ValueError("Expected a 4:3 sheet with four columns and three rows")
    cells = []
    for index in range(len(SPRITES)):
        col, row = index % 4, index // 4
        box = (col * source.width // 4, row * source.height // 3,
               (col + 1) * source.width // 4, (row + 1) * source.height // 3)
        cell = unmatte(source.crop(box))
        # Generated sheets can have faint matte noise and one-pixel dividers.
        # Measure the solid artwork, then restore its antialiased fringe from
        # the original pixels. Do not let a stray divider change sprite scale.
        solid = cell.getchannel("A").point(lambda value: 255 if value >= 192 else 0)
        bounds = solid.filter(ImageFilter.MinFilter(3)).getbbox()
        if bounds is None:
            raise ValueError(f"Missing sprite: {SPRITES[index]}")
        bounds = (max(0, bounds[0] - 3), max(0, bounds[1] - 3),
                  min(cell.width, bounds[2] + 3), min(cell.height, bounds[3] + 3))
        cell = cell.crop(bounds)
        if index in (0, 1, 2, 9, 10, 11):
            # These source materials are neutral. Remove residual chroma from
            # the matte's edge without changing coverage or the amber state.
            neutral = ImageOps.grayscale(cell).convert("RGBA")
            neutral.putalpha(cell.getchannel("A"))
            cell = neutral
        cells.append(cell)
    return cells


def pack(cells):
    atlas = Image.new("RGBA", (1024, 1024))
    entries = []
    for index, (name, cell) in enumerate(zip(SPRITES, cells)):
        cell.thumbnail((SPRITE_SIZE, SPRITE_SIZE), Image.Resampling.LANCZOS)
        x = (index % 4) * CELL_SIZE + GUTTER
        y = (index // 4) * CELL_SIZE + GUTTER
        atlas.paste(cell, (x, y))
        entries.append(f"    {name}: {x}px {y}px {cell.width}px {cell.height}px;")
        if name in ("glass-shop", "glass-character", "glass-inventory", "glass-friends", "glass-menu"):
            # Keep utility pictograms square inside the native portrait buttons.
            inset = round(cell.width * 0.17)
            entries.append(f"    {name}-icon: {x + inset}px {y + inset}px {cell.width - 2 * inset}px {cell.height - 2 * inset}px;")
        if name == "glass-panel":
            entries.append(f"    glass-panel-inner: {x + 22}px {y + 22}px {cell.width - 44}px {cell.height - 44}px;")
        if name == "glass-rail":
            for suffix, left, width in [("left", 0, 28), ("middle", 28, cell.width - 56), ("right", cell.width - 28, 28)]:
                entries.append(f"    glass-rail-{suffix}: {x + left}px {y}px {width}px {cell.height}px;")
    return atlas, entries


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    with Image.open(args.source) as source:
        atlas, entries = pack(extract_cells(source))
    args.destination.mkdir(parents=True, exist_ok=True)
    (args.destination / "black-glass.OZT").write_bytes(encode(atlas))
    stylesheet = "/* Generated by tools/pack_hud_atlas.py; true straight-alpha cutouts. */\n"
    stylesheet += '@spritesheet black-glass {\n    src: "black-glass.tga";\n'
    (args.destination / "black_glass_sprites.rcss").write_text(stylesheet + "\n".join(entries) + "\n}\n")
    print(f"Packed {len(SPRITES)} sprites, {atlas.width}x{atlas.height}; alpha range {atlas.getchannel('A').getextrema()}")


if __name__ == "__main__":
    main()
